# Generated by Django 5.2.7 on 2025-12-26 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=32, unique=True),
        ),
    ]
