# Generated by Django 5.2.7 on 2025-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_retirada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RETIRADA', 'Retirar na Loja'), ('ENTREGA', 'Entregar no Endereço')], default='RETIRADA', max_length=20),
        ),
    ]
