# Generated by Django 5.2.7 on 2026-01-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_data_devolucao_pedido_data_retirada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='quantidade',
            new_name='quantidade_estoque',
        ),
    ]
