# Generated by Django 5.2.7 on 2026-01-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_rename_quantidade_itempedido_quantidade_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('SEPARANDO', 'Separando'), ('PRONTO', 'Pronto para retirada'), ('EM_USO', 'Em uso (Alugado)'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20),
        ),
    ]
