# Generated by Django 5.2.7 on 2025-10-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_imagem_produto_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='banner',
            field=models.BooleanField(default=False, help_text='Exibir no banner principal'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Destacar esta categoria'),
        ),
        migrations.AddField(
            model_name='kit',
            name='banner',
            field=models.BooleanField(default=False, help_text='Exibir no banner principal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='banner',
            field=models.BooleanField(default=False, help_text='Exibir no banner principal'),
        ),
    ]
