# Generated by Django 5.2.7 on 2025-11-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_categoria_banner_categoria_destaque_kit_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='banner',
        ),
    ]
