# Generated by Django 5.2.7 on 2025-12-31 13:42

import django.db.models.deletion
import produto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_categoria_banner_remove_kit_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, help_text='Usado na URL (ex: casamento-rustico)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='codigo',
            field=models.CharField(default=produto.models.gerar_codigo_unico, help_text='Código único do kit', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=produto.models.gerar_codigo_unico, help_text='Código único do produto (ex: PRT001)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('verde', 'Verde'), ('rosa', 'Rosa'), ('azul', 'Azul'), ('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('dourado', 'Dourado'), ('prateado', 'Prateado'), ('lilas', 'Lilás'), ('transparente', 'Transparente'), ('outra', 'Outra')], default='branco', help_text='Essencial para o filtro de cores funcionar', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='destaque',
            field=models.BooleanField(default=False, help_text="Exibir na home como 'Estilo de Evento'?"),
        ),
        migrations.AlterField(
            model_name='kit',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Aparece na seção Destaques da Home'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem principal do Kit', null=True, upload_to='kits/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem principal (Capa)', null=True, upload_to='produtos/'),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/galeria/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='produto.produto')),
            ],
        ),
    ]
