# Generated by Django 5.2.7 on 2026-01-02 19:09

import django.db.models.deletion
import produto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_categoria_slug_kit_codigo_produto_codigo_produto_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=1, verbose_name='Estoque Total'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_carrossel', to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='codigo',
            field=models.CharField(default=produto.models.gerar_codigo_unico, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kit',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='kits/'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se deixar vazio, será a soma dos produtos.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=produto.models.gerar_codigo_unico, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('verde', 'Verde'), ('rosa', 'Rosa'), ('azul', 'Azul'), ('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('dourado', 'Dourado'), ('prateado', 'Prateado'), ('lilas', 'Lilás'), ('transparente', 'Transparente'), ('outra', 'Outra')], default='branco', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço unitário do aluguel', max_digits=10),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantas unidades desse produto vão no kit?')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produto.kit')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Item do Kit',
                'verbose_name_plural': 'Itens do Kit',
                'unique_together': {('kit', 'produto')},
            },
        ),
    ]
