# Generated by Django 5.2.7 on 2026-01-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_remove_kit_produtos_remove_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='produtos',
            field=models.ManyToManyField(related_name='kits', through='produto.KitItem', to='produto.produto'),
        ),
    ]
