# Generated by Django 5.2.7 on 2026-01-03 18:06

import django.db.models.deletion
import produto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_kit_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=produto.models.gerar_codigo_unico, max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Ex: Casamento Rústico Completo', max_length=150)),
                ('tipo', models.CharField(choices=[('casamento', 'Casamento'), ('aniversario', 'Aniversário'), ('corporativo', 'Corporativo'), ('formatura', 'Formatura'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Evento')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('destaque', models.BooleanField(default=False)),
                ('capacidade_pessoas', models.PositiveIntegerField(default=50, help_text='Capacidade estimada de convidados para este pacote')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Se deixar vazio, será a soma dos produtos.', max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade necessária para este evento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_evento', to='produto.evento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Item do Evento',
                'verbose_name_plural': 'Itens do Evento',
                'unique_together': {('evento', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='produtos',
            field=models.ManyToManyField(related_name='eventos', through='produto.EventoItem', to='produto.produto'),
        ),
    ]
